# Generated by Django 5.0.6 on 2024-07-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInOneModel',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.productmodel')),
            ],
            bases=('product.productmodel',),
        ),
        migrations.CreateModel(
            name='AssembledCaseModel',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.productmodel')),
            ],
            bases=('product.productmodel',),
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.productmodel')),
            ],
            bases=('product.productmodel',),
        ),
    ]
