# Generated by Django 5.0.6 on 2024-07-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_allinonemodel_assembledcasemodel_laptopmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledcasemodel',
            name='cpu',
            field=models.ManyToManyField(to='product.cpumodel'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='fan_cpu',
            field=models.ManyToManyField(to='product.fancpumodel'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='gpu',
            field=models.ManyToManyField(blank=True, null=True, to='product.gpumodel'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='hard',
            field=models.ManyToManyField(to='product.hardmodel'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='main_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.mainboardmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='ram',
            field=models.ManyToManyField(to='product.rammodel'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='ssd',
            field=models.ManyToManyField(to='product.ssdmodel'),
        ),
    ]
