# Generated by Django 5.0.6 on 2024-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_assembledcasemodel_cpu_assembledcasemodel_fan_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembledcasemodel',
            name='gpu',
            field=models.ManyToManyField(blank=True, to='product.gpumodel'),
        ),
    ]
