# Generated by Django 5.0.6 on 2024-07-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_assembledcasemodel_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledcasemodel',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.casemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='optical_drive',
            field=models.ManyToManyField(null=True, to='product.opticaldrivemodel'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='power',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.powermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assembledcasemodel',
            name='hard',
            field=models.ManyToManyField(blank=True, to='product.hardmodel'),
        ),
        migrations.AlterField(
            model_name='assembledcasemodel',
            name='ssd',
            field=models.ManyToManyField(blank=True, to='product.ssdmodel'),
        ),
    ]
