# Generated by Django 5.0.6 on 2024-07-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_assembledcasemodel_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopCpuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='پردازنده')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopGpuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='گرافیک')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopGpuStorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='حافظه گرافیک')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopHardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='هارد')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopRamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='رم')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopResolutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='رزولوشن')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopScreenSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='سایز صفحه نمایش')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopSSDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True, verbose_name='اس اس دی')),
            ],
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='battery_storage',
            field=models.PositiveIntegerField(default=1, verbose_name='ظرفیت باتری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='on_site_gpu',
            field=models.BooleanField(default=1, verbose_name='گرافیک مجزا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='power_adaptor',
            field=models.PositiveIntegerField(default=1, verbose_name='اداپتور پاور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='weight',
            field=models.FloatField(default=1, verbose_name='وزن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bittypemodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='cpucoremodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='cpuplatformmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ddrmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='fancpuplatformmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='formfactormodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='gpuddrmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='gpuplatformmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='hardtypemodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='mainboardchipsetmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='onboardgpumodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='powerformfactormodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ramfrequencymodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ramplatformmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='satatypemodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sockettypemodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ssdtypemodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='cpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopcpumodel', verbose_name='پردازنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='gpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopgpumodel', verbose_name='گرافیک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='gpu_storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopgpustoragemodel', verbose_name='حافظه پردازنده گرافیکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='hard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptophardmodel', verbose_name='هارد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='ram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptoprammodel', verbose_name='رم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='resolution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopresolutionmodel', verbose_name='رزولوشن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='screen_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopscreensizemodel', verbose_name='ابعاد صفحه نمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='ssd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopssdmodel', verbose_name='اس اس دی'),
            preserve_default=False,
        ),
    ]
