# Generated by Django 5.0.6 on 2024-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_laptopcpumodel_laptopgpumodel_laptopgpustoragemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembledcasemodel',
            name='gpu',
            field=models.ManyToManyField(blank=True, related_name='main_board_assembled_cases', to='product.gpumodel', verbose_name='کارت گرافیک'),
        ),
    ]
