# Generated by Django 5.0.6 on 2024-07-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_assembledcasemodel_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembledcasemodel',
            name='gpu',
            field=models.ManyToManyField(blank=True, to='product.gpumodel', verbose_name='کارت گرافیک'),
        ),
        migrations.AlterField(
            model_name='assembledcasemodel',
            name='main_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_board_assembled_cases', to='product.mainboardmodel', verbose_name='مادربرد'),
        ),
    ]
