# Generated by Django 5.0.6 on 2024-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazingoffermodel',
            name='order',
        ),
        migrations.AlterField(
            model_name='amazingoffermodel',
            name='expired_date',
            field=models.DateTimeField(),
        ),
    ]
