# Generated by Django 5.0.6 on 2024-07-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_amazingoffermodel_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantoffermodel',
            name='order',
        ),
    ]
