# Generated by Django 5.0.6 on 2024-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_instantoffermodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantoffermodel',
            name='expired_date',
            field=models.DateTimeField(),
        ),
    ]
