# Generated by Django 5.0.6 on 2024-07-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_instantoffermodel_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetailmodel',
            name='copy_right',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='enamad_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_detail/image'),
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='enamad_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='kasbokar_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_detail/image'),
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='kasbokar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='samandehi_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_detail/image'),
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='samandehi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetailmodel',
            name='amazing_products_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_detail/image'),
        ),
        migrations.AlterField(
            model_name='sitedetailmodel',
            name='empty_cart_image',
            field=models.ImageField(upload_to='site_detail/image'),
        ),
        migrations.AlterField(
            model_name='sitedetailmodel',
            name='logo',
            field=models.ImageField(upload_to='site_detail/image'),
        ),
        migrations.AlterField(
            model_name='sitedetailmodel',
            name='suggested_products_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_detail/image'),
        ),
    ]
